<?php use Carbon\Carbon; ?>
<table class="table table-stripped">
    <thead>
        <tr>
            <th>Order Id</th>
            <th>Date</th>
            <th>Type</th>
            <th>Customer Name</th>
            <th>Contact No</th>
            <th>Generated At</th>
            <th>Generated By</th>
            <th>Assigned At</th>
            <th>Assigned By</th>
            <th>Accepted At</th>
            <th>Accepted By</th>
            <th>In-Progress At</th>
            <th>In-Progress By</th>
            <th>Completed At</th>
            <th>Completed By</th>
            <th>Total Time</th>
            <th>State</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($orderTimeLine as $key=> $timeLine)
            <tr>
                <td>{{$key}}</td>
                <td>{{date('d-M-y',strtotime($timeLine[0]->DelDate))}}</td>
                <td>{{$timeLine[0]->type}}</td>
                <td>{{$timeLine[0]->shipping_first_name}}</td>
                <td>{{$timeLine[0]->contact_no}}</td>
                <td>{{date('d-M-y',strtotime($timeLine[0]->log_date))." ".date('H:i:s',strtotime($timeLine[0]->log_time))}}</td>
                <td>{{$timeLine[0]->updated_by}}</td>
                <td>@if(isset($timeLine[1]))
                        {{date('d-M-y',strtotime($timeLine[1]->log_date))." ".date('H:i:s',strtotime($timeLine[1]->log_time))}}
                    @endif
                </td>
                <td>@if(isset($timeLine[1])){{$timeLine[1]->updated_by}}@endif</td>
                <td>@if(isset($timeLine[2]))
                    {{date('d-M-y',strtotime($timeLine[2]->log_date))." ".date('H:i:s',strtotime($timeLine[2]->log_time))}}
                    @endif
                </td>
                <td>@if(isset($timeLine[2])){{$timeLine[2]->updated_by}}@endif</td>
                <td>@if(isset($timeLine[3]))
                        {{date('d-M-y',strtotime($timeLine[3]->log_date))." ".date('H:i:s',strtotime($timeLine[3]->log_time))}}
                    @endif
                </td>
                <td>@if(isset($timeLine[3])){{$timeLine[3]->updated_by}}@endif</td>
                <td>@if(isset($timeLine[4]))
                        {{date('d-M-y',strtotime($timeLine[4]->log_date))." ".date('H:i:s',strtotime($timeLine[4]->log_time))}}
                    @elseif($timeLine[0]->del_status == "Picked up" || $timeLine[0]->del_status == "Collected" || $timeLine[0]->del_status == "Delivered")
                        {{date('d-M-y',strtotime($timeLine[0]->completed_at))." ".date('H:i:s',strtotime($timeLine[0]->completed_at))}}
                    @endif
                </td>
                <td>@if(isset($timeLine[4])){{$timeLine[4]->updated_by}}
                    @elseif($timeLine[0]->del_status == "Picked up" || $timeLine[0]->del_status == "Collected" || $timeLine[0]->del_status == "Delivered"){{$timeLine[0]->updatedBy}}
                    @endif</td>
                <td>
                    @if(isset($timeLine[4]))
                        @php
                            $completed_date = Carbon::parse(date('d-M-y',strtotime($timeLine[4]->log_date))." ".date('H:i:s',strtotime($timeLine[4]->log_time)));
                            $assigned_date = Carbon::parse(date('d-M-y',strtotime($timeLine[0]->log_date))." ".date('H:i:s',strtotime($timeLine[0]->log_time)));

                            $diff = $completed_date->diffInSeconds($assigned_date);
                        @endphp
                        {{gmdate('H:i:s', $diff)}}
                    @else
                        @if($timeLine[0]->del_status == "Picked up" || $timeLine[0]->del_status == "Collected" || $timeLine[0]->del_status == "Delivered")
                        @php
                            $completed_date = Carbon::parse(date('d-M-y',strtotime($timeLine[0]->completed_at))." ".date('H:i:s',strtotime($timeLine[0]->completed_at)));
                            $assigned_date = Carbon::parse(date('d-M-y',strtotime($timeLine[0]->log_date))." ".date('H:i:s',strtotime($timeLine[0]->log_time)));

                            $diff = $completed_date->diffInSeconds($assigned_date);
                        @endphp
                        {{gmdate('H:i:s', $diff)}}
                        @else
                            <b>{{"Not Completed"}}</b>
                        @endif
                    @endif
                </td>
                <td>
                    @if(isset($timeLine[4]))
                        @php
                            $completed_date = Carbon::parse(date('d-M-y',strtotime($timeLine[4]->log_date))." ".date('H:i:s',strtotime($timeLine[4]->log_time)));
                            $assigned_date = Carbon::parse(date('d-M-y',strtotime($timeLine[0]->log_date))." ".date('H:i:s',strtotime($timeLine[0]->log_time)));

                            $diff = $completed_date->diffInSeconds($assigned_date);
                            $state = "On Time";
                            if(date('H:i:s',strtotime(gmdate('H:i:s', $diff))) >= date('H:i:s',strtotime('04:00:00')))
                            {
                                $state = "Delayed";
                            }
                            else
                            {
                                $state = "On Time";
                            }
                        @endphp
                        {{$state}}
                    @else
                        @if($timeLine[0]->del_status == "Picked up" || $timeLine[0]->del_status == "Collected" || $timeLine[0]->del_status == "Delivered")
                        @php
                            $completed_date = Carbon::parse(date('d-M-y',strtotime($timeLine[0]->completed_at))." ".date('H:i:s',strtotime($timeLine[0]->completed_at)));
                            $assigned_date = Carbon::parse(date('d-M-y',strtotime($timeLine[0]->log_date))." ".date('H:i:s',strtotime($timeLine[0]->log_time)));

                            $diff = $completed_date->diffInSeconds($assigned_date);
                            $state = "On Time";
                            if(date('H:i:s',strtotime(gmdate('H:i:s', $diff))) >= date('H:i:s',strtotime('04:00:00')))
                            {
                                $state = "Delayed";
                            }
                            else
                            {
                                $state = "On Time";
                            }
                        @endphp
                        {{$state}}
                        @else
                            <b>{{"Pending"}}</b>
                        @endif
                    @endif
                </td>
            </tr>
        @endforeach
    </tbody>
</table>