<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tax Invoice</title>
    {{-- <link href="{{url('/')}}/assets/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css"> --}}
    {{-- <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet"> --}}
    <!-- Custom styles for this page -->
    {{-- <link href="{{url('/')}}/assets/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet"> --}}
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.2/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  
</head>
<body>
    <div class="container-fluid">
        {{-- <center><h4>Tax Invoice</h4></center> --}}
        <table>
            <tbody>
                <tr>
                    <td>
                        <img src="<?php echo url('/');?>/assets/images/logo_small.png">
                    </td>
                    <td>
                        <h3>Quali55Care & Consulting Private Limited</h3>
                    </td>
                </tr>
            </tbody>
        </table>
    
        <table class="table table-sm main-table">
            <tbody>
                <tr>
                    <td>
                        <b>{{$order->first()->customer_name}}</b><br>
                        {{-- {{$order->first()->address_line_1}}, {{$order->first()->address_line_1}}<br>
                        {{$order->first()->area}} , {{$order->first()->landmark}}<br>
                        {{$order->first()->city}} - {{$order->first()->pincode}}<br> --}}
                    </td>
                    <td>
                        <span>Quote No.</span><br>
                        <span id="Quoteno"><b>{{$order->first()->quote_id}}</b></span>
                    </td>
                    <td>
                        <span>Date</span><br>
                        <span id=""><b>{{date('d-M-Y',strtotime($order->first()->quote_date))}}</b></span>
                    </td>
                    <td>
                        <span>Generated By</span><br>
                        <span id=""><b>{{$order->first()->created_by}}</b></span>
                    </td>
                </tr>
            </tbody>
        </table>
        <table class="table table-sm table-bordered border-dark">
            <tbody id="product-body">
                <tr>
                    <th>Sr.No</th>
                    <th>Product</th>
                    <th>Purchase Type</th>
                    <th>Qty</th>
                    <th>Rate</th>
                    <th>Period</th>
                    <th>Amount</th>
                    <th>Image</th>
                </tr>
            </tbody>
            <tbody>
                @forelse ($order as $key=>$product)
                    <tr>
                        <td>{{++$key}}</td>
                        <td>{{ucfirst($product->product_name)}}</td>
                        <td>{{ucfirst($product->purchase_type)}}</td>
                        <td>{{$product->quantity}}</td>
                        <td>{{($product->purchase_type=='rent') ? $product->rent : $product->sale}}</td>
                        <td>
                            @if($product->purchase_type=='rent')
                                {{$product->frequency}} {{$product->frequency_type}}
                            @else
                                -
                            @endif
                        </td>
                        <td>{{$product->amount}}</td>
                        <td>
                            <img src="{{$product->product_img_url}}"  alt="" width="150px" height="150px">
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="8">No Products</td>
                    </tr>
                @endforelse
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="6" class="text-right">Total</th>
                    <th>{{$order->pluck('amount')->sum()}}</th>
                    <th></th>
                </tr>
            </tfoot>
        </table>
        <span>Delivery with installation <b>{{$order->first()->transport_amt}}</b> including pickup and drop, All the payments are non refundable  irrespective of utilization. We advise ICU nurse to look after patient support.</span>
    </div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>