@extends('header_and_sidebar')

@section('styles')
@endsection

@section('content')
    @if(session()->has('message'))
        <div class="alert alert-success mt-2">
            {{ session()->get('message') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif
    @if(session()->has('error'))
        <div class="alert alert-danger mt-2">
            {{ session()->get('error') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif
    <div class="card mt-2">
        <div class="card-header">
            <form action="{{route('quote.index')}}" method="get">
                @csrf
                <div class="row">
                    <div class="col-md-2">
                        <button type="button" class="btn btn-outline-primary btn-sm btn-block" id="btncreatequote">Create Quote</button>
                    </div>
                    <div class="col-md-2">
                        <input type="text" class="form-control form-control-sm" name="search_customer_name" id="" placeholder="Customer Name" value="{{request()->get('search_customer_name')}}">
                    </div>
                    <div class="col-md-2">
                        <input type="text" class="form-control form-control-sm" name="search_contact_no" id="" placeholder="Contact No" value="{{request()->get('search_contact_no')}}">
                    </div>
                    <div class="col-md-2">
                        <select class="selectpicker form-control border border-dark" name="search_products[]" id="" data-live-search="true" data-size="5" title="Select Products" multiple>
                            @forelse ($products as $Key=>$product)
                                <option value="{{$product->id}}" @if(!empty(request()->get('search_products')) && in_array($product->id,request()->get('search_products'))) selected @endif>{{$product->product_name}}</option>
                            @empty
                                <option value="" selected disabled>No Products</option>
                            @endforelse
                        </select>
                    </div>
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-sm btn-outline-primary">Submit</button>
                        <a href="{{route('quote.index')}}" class="btn btn-sm btn-outline-secondary">clear</a>
                    </div>

                </div>
            </form>
        </div>
        <div class="table table-responsive">
            <table class="table">
                <thead>
                    <th>Customer Name</th>
                    <th>Contact No</th>
                    <th>Products</th>
                    <th>Amount</th>
                    @if(session('role')=='admin' || session('role')=='superuser')<th>Generated By</th>@endif
                    <th>Action</th>
                </thead>
                <tbody>
                    @forelse ($orders as $key=>$order)
                        <tr>
                            <td>{{$order->first()->customer_name}}</td>
                            <td>{{$order->first()->contact_no}}</td>
                            <td>{{$order->pluck('product_name')->implode(', ')}}</td>
                            <td>{{$order->pluck('amount')->sum()}}</td>
                            @if(session('role')=='admin' || session('role')=='superuser')
                                <td>{{$order->first()->created_by}}</td>
                            @endif
                            <td class="text-nowrap">
                                @if($order->first()->status!='cancel')
                                    <button class="btn btn-outline-primary btn-sm edit-order" data-customer_id = {{$key}}>Edit</button>
                                    <a class="btn btn-outline-secondary btn-sm" href="{{route('quote.show',$key)}}" target="_blank"> PDF</a>
                                    <button class="btn btn-outline-danger btn-sm cancel-order" data-customer_id = {{$key}} data-customer_name ="{{$order->first()->customer_name}}" >Cancel</button>
                                @else
                                    <span class="badge badge-danger">Cancelled</span>
                                @endif
                            </td>
                        </tr>    
                    @empty
                        
                    @endforelse
                </tbody>
            </table>
            {{$orders->withPath(url()->full())->links('Custom.Pagination.pagination')}}
        </div>
    </div>

    <div class="modal fade" id="create_update_quote_modal" tabindex="-1" role="dialog" aria-labelledby="create_update_quote_modalTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title text-primary" id="create_update_quote_modalTitle">Create Quote</h5>
                    <button type="button" class="close btn-sm" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{route('quote.store')}}" method="POST" id="quoteform">
                    @csrf
                    @method('PUT')
                    {{-- <input type="hidden" name="_method" id="_method" value="PUT"> --}}
                    <div class="modal-body">
                        <div class="customer">
                            <div class="row">
                                <div class="col-md-4">
                                    <label for="">Contact No</label>
                                    <input type="number" class="form-control form-control-sm" name="contact_no" id="contact_no" minlength="10" required>
                                </div>
                                <div class="col-md-4">
                                    <label for="">Customer Name</label>
                                    <input type="text" class="form-control form-control-sm" name="customer_name" id="customer_name" required>
                                </div>
                                <div class="col-md-4">
                                    <label for="">Gender</label>
                                    <div class="btn-group btn-group-toggle btn-block btn-sm" data-toggle="buttons">
                                        <label class="btn btn-outline-primary btn-sm active" id="radio_male_lbl">
                                            <input type="radio" name="gender" id="radio_male" checked value="male">Male
                                        </label>
                                        <label class="btn btn-outline-primary btn-sm" id="radio_female_lbl">
                                            <input type="radio" name="gender" id="radio_female" value="female">Female
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <label for="">Address Line 1</label>
                                    <input type="text" class="form-control form-control-sm" name="address_line_1" id="address_line_1" required>
                                </div>
                                <div class="col-md-4">
                                    <label for="">Address Line 2</label>
                                    <input type="text" class="form-control form-control-sm" name="address_line_2" id="address_line_2">
                                </div>
                                <div class="col-md-4">
                                    <label for="">Area</label>
                                    <input type="text" class="form-control form-control-sm" name="area" id="area" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <label for="">Landmark</label>
                                    <input type="text" class="form-control form-control-sm" name="landmark" id="landmark" required>
                                </div>
                                <div class="col-md-4">
                                    <label for="">City</label>
                                    <select class="form-control form-control-sm" name="city" id="city" required>
                                        <option value="Mumbai" selected>Mumbai</option>
                                        <option value="Pune">Pune</option>
                                    </select>
                                </div>
                                <div class="col-md-4">
                                    <label for="">Pincode</label>
                                    <input type="number" class="form-control form-control-sm" name="pincode" id="pincode" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <label for="">Date</label>
                                    <input type="date" class="form-control form-control-sm" name="quote_date" id="quote_date" value="{{date('Y-m-d')}}" required>
                                </div>
                                <div class="col-md-4">
                                    <label for="">Transport</label>
                                    <input type="number" class="form-control form-control-sm" name="transport_amt" id="transport_amt" value="" required>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="products">
                            <div class="row">
                                <div class="col-md-2 d-flex align-items-end">
                                    <button type="button" class="btn btn-outline-primary btn-sm btn-block" id="btn_product_add">Add Product</button>
                                </div>
                            </div>
                            <div class="row products-table mt-1 px-2">
                                <div class="table table-responsive">
                                    <table class="table" id="quote_product_table">
                                        <thead>
                                            <th>Product Name</th>
                                            <th>Purchase Type</th>
                                            <th>Rate</th>
                                            <th>Period</th>
                                            <th>Period Type</th>
                                            <th>Quantity</th>
                                            <th>Total</th>
                                            <th>Action</th>
                                        </thead>
                                        <tbody id="quote_products_table_body"></tbody>
                                        {{-- <tfoot>
                                            <th colspan="6" class="text-right">Total</th>   
                                            <th><span id="totalrate">0</span></th>
                                            <th></th>
                                        </tfoot> --}}
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>                
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-sm btn-primary">Save</button>
                        <button type="button" class="btn btn-sm btn-secondary" onclick="$('.loading-spinner').show();$('.ccad-modal-content').show();" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="modal fade" id="quoteCancelModal" tabindex="-1" role="dialog" aria-labelledby="quoteCancelModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <form action="" method="post" id="cancel_quote_form">
                @csrf
                @method('DELETE')
                <div class="modal-header">
                <h5 class="modal-title" id="quoteCancelModalLabel">Cancel Quote</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="customer_id" id="cancel_customer_id">
                    Are you sure to cancel this Quote "<b><span id="quote_cancel_customer_name"></span></b>" ?
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </form>
          </div>
        </div>
    </div>

@endsection

@section('script')
<script>
    $('#btncreatequote').on('click',function(){
        trcount = 0;
        $('#quote_products_table_body').empty();
        $('#quoteform').attr('method','POST')
        //$('#_method').val('POST');
        $('input[name=_method]').val('POST');
        let route = '{{route('quote.store')}}';
        $("#quoteform").attr('action',route);
        //$(".ccad-form").attr('method',"PUT");
        $('#contact_no').val(null);
        $('#customer_name').val(null);
        $('#address_line_1').val(null);
        $('#address_line_2').val(null);
        $('#area').val(null);
        $('#landmark').val(null);
        $('#city').val('Mumbai');
        $('#pincode').val(null);
        $('#radio_male').prop('checked',true);
        $('#radio_female').prop('checked',false);
        $('#radio_male_lbl').addClass('active');
        $('#radio_female_lbl').removeClass('active');

        let today = "{{date('Y-m-d')}}";
        $('#quote_date').val(today);
        $('#create_update_quote_modalTitle').text('Create Quote');
        $('#create_update_quote_modal').modal("show");
    })
    var trcount=parseInt($('#quote_products_table_body tr:last').attr('id'));
    $('#btn_product_add').on('click',function(){
        // let purchase_type = $('#select_purchase_type').val();
        // let period = $('#inp_period').val();
        // let period_type = $('#select_period_type').val();
        // let quantity = $('#inp_quantity').val();
        // let product = $('#select_product').val();
        // let rate = $('#inp_rate').val();
        // let product_name = $('#select_product').find("option:selected").text();
        let totalrate = 0;
        let products_arr = @json($products);
        if(isNaN(trcount))
        {
            trcount = 0;
        }
        $('.product_select').selectpicker('render');
        var row="<tr id='tr"+trcount+"'>";
                row+="<td class='text-nowrap'>";
                    row+="<select class='selectpicker form-control product_select calculate' id='product_select"+trcount+"' data-trcount='"+trcount+"' title='Select Product' data-width='fit' data-size='5' data-live-search='true' name='product[product_id][]' onchange='calculate(this)' required>";
                        $.each(products_arr,function(key,value){
                            row+="<option value='"+value.id+"'>"+value.product_name+"</option>";
                        });
                    row+="</select>";
                row+="</td>";
                row+="<td>";
                    row+="<div class='btn-group btn-group-toggle btn-block btn-sm calculate' data-toggle='buttons' data-trcount='"+trcount+"'>";
                            row+="<label class='btn btn-outline-primary btn-sm active' id='radio_rent_lbl"+trcount+"' data-trcount='"+trcount+"'>";
                            row+="<input type='radio' name='product[purchase_type][]"+trcount+"' id='radio_rent"+trcount+"' checked value='rent' data-trcount='"+trcount+"' onchange='purchaseType(this)'>Rent</label>";
                            row+="<label class='btn btn-outline-primary btn-sm' id='radio_sale_lbl"+trcount+"' data-trcount='"+trcount+"'>";
                            row+="<input type='radio' name='product[purchase_type][]"+trcount+"' id='radio_sale"+trcount+"' value='sale' data-trcount='"+trcount+"' onchange='purchaseType(this)'>Sale</label>";
                    row+="</div>";
                row+="</td>";    
                row+="<td><input type='number' class='form-control form-control-sm calculate' name='product[rate][]' id='rate"+trcount+"' data-trcount='"+trcount+"' value='0' oninput='calculate(this)' required></td>";
                row+="<td><input type='number' class='form-control form-control-sm calculate' name='product[period][]' id='period"+trcount+"' data-trcount='"+trcount+"' value='1' oninput='calculate(this)' required></td>";
                row+="<td>";    
                    row+="<select class='form-control form-control-sm calculate' name='product[period_type][]' id='period_type"+trcount+"' data-trcount='"+trcount+"' onchange='calculate(this)' required>";
                        row+="<option value='day'>Day</option>";
                        row+="<option value='week'>Week</option>";
                        row+="<option value='month' selected>Month</option>";
                    row+="</select>";
                row+="</td>";
                row+="<td><input type='number' class='form-control form-control-sm calculate' name='product[quantity][]' id='quantity"+trcount+"' data-trcount='"+trcount+"' value='1' oninput='calculate(this)' required></td>";
                row+="<td><span id='product_total"+trcount+"'>0</span></td>";    
                row+="<td><button type='button' class='btn btn-outline-danger btn-sm btn-block btn_product_remove' id='btn_product_remove' onclick='removeProduct(this,"+trcount+")'>Remove</button></td>";
            row+="</tr>";
        $('.product_select').selectpicker('render');
        $('#quote_product_table tbody').append(row);
        $('#product_select'+trcount).selectpicker('render');
        trcount = trcount + 1;
        $('#create_update_quote_modal').modal("show")
        // $('#totalrate').text(totalrate);
        // $('.product_select').selectpicker('render');
        
    });

    function removeProduct(e,num){
        $('#tr'+num).remove();
    }
   
    function calculate(e){
        let id = e.id;
        let trcount = $('#'+id).data('trcount');
        let rate = $('#rate'+trcount).val();
        let period = $('#period'+trcount).val();
        let quantity = $('#quantity'+trcount).val();
        let product_total = 0;
        let total = 0;
        product_total = rate*quantity;
        $('#product_total'+trcount).text(product_total);

    }
    $('.edit-order').on('click',function(){
        let cust_id = $(this).data('customer_id');
        $('#quoteform').attr('method','POST')
        //$('#_method').val('PUT');
        $('input[name=_method]').val('PUT');
        let route = "{{url('/')}}"+'/quote/'+cust_id;
        $("#quoteform").attr('action',route);
        var dataString = ({_token:"{{ csrf_token() }}"});
        $('#create_update_quote_modalTitle').text('Update Quote');
        $.ajax({
            type: "GET",
            url: "{{url('/')}}/quote/"+cust_id+"/edit",
            data: dataString,
            cache:false,
            success: function (data)
            {
                $('#quote_products_table_body').empty();
                let products_arr = @json($products);
                //customer details
                $('#contact_no').val(data[0].contact_no);
                $('#customer_name').val(data[0].customer_name);
                $('#address_line_1').val(data[0].address_line_1);
                $('#address_line_2').val(data[0].address_line_2);
                $('#area').val(data[0].area);
                $('#landmark').val(data[0].landmark);
                $('#city').val(data[0].city);
                $('#pincode').val(data[0].pincode);
                $('#quote_date').val(data[0].quote_date);
                $('#transport_amt').val(data[0].transport_amt);
                if(data[0].gender=='male'){
                    $('#radio_male').prop('checked',true);
                    $('#radio_female').prop('checked',false);
                    $('#radio_male_lbl').addClass('active');
                    $('#radio_female_lbl').removeClass('active');
                }else{
                    $('#radio_female').prop('checked',true);
                    $('#radio_male').prop('checked',false);
                    $('#radio_female_lbl').addClass('active');
                    $('#radio_male_lbl').removeClass('active');
                }

                var row="";
                $.each(data,function(key,order_product){
                    row+="<tr id='tr"+key+"'>";
                        row+='<input type="hidden" name="product[qp_id][]" value="'+order_product.qp_id+'">';
                        row+="<td class='text-nowrap'>";
                            row+="<select class='selectpicker form-control product_select calculate' id='product_select"+key+"' data-trcount='"+key+"' title='Select Product' data-width='fit' data-size='5' data-live-search='true' name='product[product_id][]' onchange='calculate(this)' required>";
                                $.each(products_arr,function(product_key,product){
                                    row+='<option value="'+product.id+'" '+(product.id==order_product.product_id ? 'selected' : '')+'>'+product.product_name+'</option>';
                                });
                            row+="</select>";
                        row+="</td>";
                        row+="<td>";
                            row+="<div class='btn-group btn-group-toggle btn-block btn-sm calculate' data-toggle='buttons' data-trcount='"+key+"'>";
                                row+='<label class="btn btn-outline-primary btn-sm '+(order_product.purchase_type=='rent' ? 'active' : '')+'" id="radio_rent_lbl'+key+'" data-trcount='+key+'>';
                                row+='<input type="radio" name="product[purchase_type][]'+key+'" id="radio_rent'+key+'" '+(order_product.purchase_type=='rent' ? 'checked' : '')+' value="rent" data-trcount="'+key+'" onchange="purchaseType(this)">Rent</label>';

                                row+='<label class="btn btn-outline-primary btn-sm '+(order_product.purchase_type=='sale' ? 'active' : '')+'" id="radio_sale_lbl'+key+'" data-trcount="'+key+'">';
                                row+='<input type="radio" name="product[purchase_type][]'+key+'" id="radio_sale'+key+'" '+(order_product.purchase_type=='sale' ? 'checked' : '')+' value="sale" data-trcount="'+key+'" onchange="purchaseType(this)">Sale</label>';
                            row+="</div>";
                        row+="</td>";    
                        row+="<td><input type='number' class='form-control form-control-sm calculate' name='product[rate][]' id='rate"+key+"' data-trcount='"+key+"' value='"+order_product.rate+"' oninput='calculate(this)' required></td>";
                        row+='<td>';
                            row+='<input type="number" class="form-control form-control-sm calculate" name="product[period][]" id="period'+key+'" data-trcount="'+key+'" value="'+order_product.frequency+'" '+(order_product.purchase_type=='sale' ? 'readonly' : '')+' oninput="calculate(this)" required>';
                        row+='</td>';

                        row+="<td>";    
                            row+='<select class="form-control form-control-sm calculate" name="product[period_type][]" id="period_type'+key+'" data-trcount="'+key+'" onchange="calculate(this)" '+(order_product.purchase_type=='sale' ? 'readonly' : '')+' required>';
                                row+='<option value="month" '+(order_product.frequency_type=='day' ? 'selected' : '')+'>Day</option>';
                                row+='<option value="month" '+(order_product.frequency_type=='week' ? 'selected' : '')+'>Week</option>';
                                row+='<option value="month" '+(order_product.frequency_type=='month' ? 'selected' : '')+'>Month</option>';
                            row+="</select>";
                        row+="</td>";
                        row+="<td><input type='number' class='form-control form-control-sm calculate' name='product[quantity][]' id='quantity"+key+"' data-trcount='"+key+"' value='"+order_product.quantity+"' oninput='calculate(this)' required></td>";
                        row+="<td><span id='product_total"+key+"'>"+order_product.rate*order_product.quantity+"</span></td>";    
                        row+="<td><button type='button' class='btn btn-outline-danger btn-sm btn-block btn_product_remove' id='btn_product_remove' onclick='removeProduct(this,"+key+")'>Remove</button></td>";
                    row+="</tr>";
                    $('#product_select'+key).selectpicker('render');
                });
                $('#quote_product_table tbody').append(row);
                $('.product_select').selectpicker('render');
                trcount = data.length;
                $('#create_update_quote_modal').modal("show")
            }
        });
    })
    function purchaseType(e){
        let id = e.id;
        let trcount = $('#'+id).data('trcount');
        if(e.value=='sale'){
            $('#period'+trcount).prop('readonly',true);
            $('#period_type'+trcount).attr('readonly','true');
        }else{
            $('#period'+trcount).prop('readonly',false);
            //$('#period_type'+trcount).prop('readonly',false);
            $('#period_type'+trcount).removeAttr('readonly');
        }
    }
    $('.cancel-order').on('click',function(){
        $('#cancel_customer_id').val($(this).data('customer_id'));
        $('#quote_cancel_customer_name').text($(this).data('customer_name'));
        $('#cancel_quote_form').attr('action',"{{url('/')}}"+'/quote/'+$(this).data('customer_id'))
        $('#quoteCancelModal').modal("show");
        // alert($(this).data('customer_id'));
    });
    $('#quoteform').submit(function(event) {
        // your code here
        let contact_no = $('#contact_no').val();
        if(contact_no==null || contact_no.length!=10){
            alert('Enter 10 digit contact no');
            event.preventDefault();
        }
        if($('#quote_products_table_body tr').length==0){
            alert('Please add at least 1 product');
            event.preventDefault();
        }
    })
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
    $('.table-responsive').on('show.bs.dropdown', function () {
            $('.table-responsive').css( "overflow", "inherit" );
    });

    $('.table-responsive').on('hide.bs.dropdown', function () {
        $('.table-responsive').css( "overflow", "auto" );
    })
</script>
@endsection